//
// Generated file, do not edit! Created by opp_msgc 4.4 from queues2/test/testPacket.msg.
//

#ifndef _TESTPACKET_M_H_
#define _TESTPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>queues2/test/testPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet TestPacket {
 *     simtime_t expectedArrival;
 *     simtime_t dispatchTime;
 * }
 * </pre>
 */
class TestPacket : public ::cPacket
{
  protected:
    simtime_t expectedArrival_var;
    simtime_t dispatchTime_var;

  private:
    void copy(const TestPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TestPacket&);

  public:
    TestPacket(const char *name=NULL, int kind=0);
    TestPacket(const TestPacket& other);
    virtual ~TestPacket();
    TestPacket& operator=(const TestPacket& other);
    virtual TestPacket *dup() const {return new TestPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual simtime_t getExpectedArrival() const;
    virtual void setExpectedArrival(simtime_t expectedArrival);
    virtual simtime_t getDispatchTime() const;
    virtual void setDispatchTime(simtime_t dispatchTime);
};

inline void doPacking(cCommBuffer *b, TestPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TestPacket& obj) {obj.parsimUnpack(b);}


#endif // _TESTPACKET_M_H_
