//
// Generated file, do not edit! Created by opp_msgc 4.4 from linklayer/airframe/TbusAirFrame.msg.
//

#ifndef _TBUSAIRFRAME_M_H_
#define _TBUSAIRFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>linklayer/airframe/TbusAirFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet TbusAirFrame {
 *     bool clientMessage;
 *     string hostName;
 * }
 * </pre>
 */
class TbusAirFrame : public ::cPacket
{
  protected:
    bool clientMessage_var;
    opp_string hostName_var;

  private:
    void copy(const TbusAirFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TbusAirFrame&);

  public:
    TbusAirFrame(const char *name=NULL, int kind=0);
    TbusAirFrame(const TbusAirFrame& other);
    virtual ~TbusAirFrame();
    TbusAirFrame& operator=(const TbusAirFrame& other);
    virtual TbusAirFrame *dup() const {return new TbusAirFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getClientMessage() const;
    virtual void setClientMessage(bool clientMessage);
    virtual const char * getHostName() const;
    virtual void setHostName(const char * hostName);
};

inline void doPacking(cCommBuffer *b, TbusAirFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TbusAirFrame& obj) {obj.parsimUnpack(b);}


#endif // _TBUSAIRFRAME_M_H_
